package db;
// Generated Aug 3, 2017 1:26:36 PM by Hibernate Tools 4.3.1



/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private String korIme;
     private String ime;
     private String prezime;
     private String datumRodjenja;
     private String email;
     private String avioKomp;
     private String lozinka;

    public Korisnici() {
    }

    public Korisnici(String korIme, String ime, String prezime, String datumRodjenja, String email, String avioKomp, String lozinka) {
       this.korIme = korIme;
       this.ime = ime;
       this.prezime = prezime;
       this.datumRodjenja = datumRodjenja;
       this.email = email;
       this.avioKomp = avioKomp;
       this.lozinka = lozinka;
    }
   
    public String getKorIme() {
        return this.korIme;
    }
    
    public void setKorIme(String korIme) {
        this.korIme = korIme;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(String datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvioKomp() {
        return this.avioKomp;
    }
    
    public void setAvioKomp(String avioKomp) {
        this.avioKomp = avioKomp;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }




}


